### ISSUE TITLE
UDP payload length

### ISSUE THREAD

**Issue by MaxF12** [GrumpyOldTroll/ietf-dorms-cluster#7]
In section 3.3.1.1.1:

> When the manifest definition is at the UDP layer, it applies only to packets with IP protocol of UDP (0x11) and the payload used for calculating the packet digest includes only the UDP payload with length as the number of UDP payload octets, as calculated by subtracting the size of the UDP header from the UDP payload length.

Shouldn't this say 

> [..] as calculated by subtracting the size of the UDP header from the _IP_ payload length.

as the UDP payload length is inside the UDP header and already the desired number of UDP payload octets?

**Comment by GrumpyOldTroll** [comment]
UDP's length value is the UDP header plus payload (https://datatracker.ietf.org/doc/html/rfc768):

~~~
Length  is the length  in octets  of this user datagram  including  this
header  and the data.   (This  means  the minimum value of the length is
eight.)
~~~

The IP length value is the IP header plus IP payload, which can be larger than the UDP contents (this is the mechanism they're using for defining UDP options in the trailer space that's thus permitted to exist: https://datatracker.ietf.org/doc/html/draft-ietf-tsvwg-udp-options-15#section-3).

It's perhaps a good idea to consider more carefully whether this is the right set of data to authenticate, or whether other choices are needed.  Should there be an option to include the whole IP packet, particularly including IP options?  It's possible for an application to examine these, after all, so maybe wise to authenticate them?  But I wanted to allow for uses like mnat, which might actually discard these during an address translation step.  (It might even be possible for middle boxes to insert options, in general?)

My intent here was to allow for just authenticating the application layer data, which I think of as just the UDP payload.

**Comment by MaxF12** [comment]
Yes, of course sorry about that! Closing this for now, can open again for your comment about scope.
